name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Jekyll (optional, for Jekyll sites)
        uses: actions/setup-ruby@v1
        with: 
          ruby-version: '2.7'

      - run: gem install bundler jekyll

      - name: Build the site (Jekyll example)
        run: bundle exec jekyll buil --destination ./docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
